### PR TITLE
Notifications on song change

### PR DESCRIPTION
**Pull request by sprnza**
Hi there!
Here is my attempt to do notifications on song change. Configurable.

Thanks!

### CODE REVIEW

**Comment by inuitwallet** [comment]
Apologies for the delay again. I've been changing jobs.
I've tried this out and it works fine on my Ubuntu Machines. 
Doesn't work at all on Mac though as it seem you need different notification libraries entirely.
I don't have a Mac any more (since the job change) so I'm half thinking of just merging and making a not of that in the README.
Wondered if you have any thoughts on making this functionality an optional extra instead? Perhaps pSub needs a plugin feature?

**Comment by sprnza** [comment]
Yep, definitly must be configurable. I'll update the PR when I get some spare time.

**Comment by sammoth-ovo** [comment]
I had a go at making notifications a separate module, I hope you don't mind?
I've put the code in a separate branch for now https://github.com/mj2p/psub/tree/notifications
I'd like to find a machine that doesn't have the dependencies installed so I can see if the separation works then.

**Comment by sprnza** [comment]
No worries! Looks great, I'll test it once I get a chance. Tough times at work.

**Comment by mj2p** [comment]
notifications on song change are now in master branch. closing this PR.

**Pull request closed without merging**
